### ISSUE TITLE
Misc. Assets

### ISSUE THREAD

**Issue by dehli** [Dehli/dehli.github.io#3]

**Comment by Dehli** [comment]
![profile](https://cloud.githubusercontent.com/assets/5856011/7004344/06b7b9f6-dc38-11e4-9d85-a27419280c64.png)

**Comment by Dehli** [comment]
![dehlicp](https://cloud.githubusercontent.com/assets/5856011/7004358/34f39100-dc38-11e4-89da-c762ee8d332d.png)

**Comment by dehli** [comment]
![244-1-4](https://cloud.githubusercontent.com/assets/5856011/26706191/75da9a4a-4709-11e7-856f-3f1947458b4c.jpg)
